apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe-2
  name: fe-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-2
  strategy: {}
  template:
    metadata:
      labels:
        app: fe-2
    spec:
      imagePullSecrets:
      - name: fe-regcred
      containers:
      - image: gracehpark/foodteacher-fe-2:892d3220adedd33cbf41597b1ff6bc9d9e04f821
        name: fe-2
        ports: # 컨테이너가 개방할 포트 정의. 정의 안하면 자동 할당
        - containerPort: 3000
