apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe-dev
  name: fe-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-dev
  strategy: {}
  template:
    metadata:
      labels:
        app: fe-dev
    spec:
      imagePullSecrets:
      - name: fe-regcred
      containers:
      - image: gracehpark/foodteacher-fe-dev:90550a4cef8c35ada6e403b22c944767a273cef8
        name: fe-dev
        ports: # 컨테이너가 개방할 포트 정의. 정의 안하면 자동 할당
        - containerPort: 3000
