apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  strategy: 
    type: RollingUpdate # RollingUpdate 전략 사용
    rollingUpdate:
      maxSurge: 1 # 동시에 추가되는 최대 Pod 수
      maxUnavailable: 1 # 유지 보수 중에 동시에 사용할 수 없는 최대 Pod 수
  template:
    metadata:
      labels:
        app: fe
    spec:
      imagePullSecrets:
      - name: fe-regcred
      containers:
      - image: gracehpark/foodteacher-fe:b9f6ce8166a78e9eba5a6e147d9a08f881dfebd4
        name: fe
        ports: # 컨테이너가 개방할 포트 정의. 정의 안하면 자동 할당
        - containerPort: 3000
