apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  strategy: {}
  template:
    metadata:
      labels:
        app: fe
    spec:
      imagePullSecrets:
      - name: fe-regcred
      containers:
      - image: gracehpark/foodteacher-fe:fb6ad8f80e79920d99a8b4f336fd61e16778517d
        name: fe
        ports: # 컨테이너가 개방할 포트 정의. 정의 안하면 자동 할당
        - containerPort: 3000
      env:
      - name: NEXT_PUBLIC_API_URL 
          valueFrom:
            configMapKeyRef:
              name: fe-configmap
              key: NEXT_PUBLIC_API_URL 
      - name: NEXT_PUBLIC_KAKAO_REST_KEY 
          valueFrom:
            configMapKeyRef:
              name: fe-configmap
              key: NEXT_PUBLIC_KAKAO_REST_KEY  
