apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: be-dev
  name: be-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: be-dev
    spec:
      imagePullSecrets:
      - name: be-regcred
      containers:
      - image: gracehpark/foodteacher-be-dev:2726fb7579a6d430fb0963d4dcb06b3698286cd1
        name: be-dev
        ports: # 컨테이너가 개방할 포트 정의. 정의 안하면 자동 할당
        - containerPort: 8000
        env: # 컨테이너 환경 변수
        - name: OPENAI_API_KEY
          valueFrom:
            configMapKeyRef:
              name: be-configmap
              key: OPENAI_API_KEY
        
