apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foodteacher-be
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/foodteacher/devops.git
    targetRevision: HEAD
    path: be
  destination:
    server: https://kubernetes.default.svc
    namespace: be

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
                              
