apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mysql-config  # 로컬 경로를 실제로 적절한 경로로 수정



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2

spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

